version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/usr/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
